services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskNest
      MYSQL_USER: user_tasks
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"  # Mapea el puerto 3306 de MySQL al puerto 3307 de tu máquina
    networks:
      - app_network
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    restart: always
    environment:
      PMA_HOST: mysql  # Conecta a MySQL a través del nombre del servicio 'mysql'
      PMA_PORT: 3306  # Puerto de MySQL
      MYSQL_ROOT_PASSWORD: root  # La contraseña de root para acceder a la base de datos
    ports:
      - "8080:80"  # Accede a phpMyAdmin a través del puerto 8080 en tu máquina
    networks:
      - app_network
    depends_on:
      - mysql

networks:
  app_network:
    driver: bridge