-- init.sql
REVOKE ALL PRIVILEGES ON *.* FROM 'user_tasks'@'%';
GRANT ALL PRIVILEGES ON *.* TO 'user_tasks'@'%';
ALTER USER 'user_tasks'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;